version: '3'

services:

  mooc_mysql:
    container_name: drivania-mooc-mysql
    image: mariadb:10.6
    ports:
      - 3360:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent"]
      interval: 2s
      timeout: 10s
      retries: 10
    command: ["--default-authentication-plugin=mysql_native_password"]

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8040:8040"
      - "9040:9001"
    volumes:
      - .:/app:delegated
    command: symfony serve --dir=apps/backoffice/backend/public --port=8040 --force-php-discovery

  mooc_backend_php:
    container_name: drivania_backend-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8030:8030"
      - "9030:9001"
    volumes:
      - .:/app:delegated
    depends_on:
      - mooc_mysql
    command: symfony serve --dir=apps/mooc/backend/public --port=8030 --force-php-discovery
