app.swagger_ui:
  path: /
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

  resource: ./routes_import.yaml
    prefix: /v1

drivania_ride_service_create:
    path: /ride-services
    defaults: { _controller: App/EntryPoint/Controller/PostRideServiceController }
    methods: [POST]

drivania_ride_service_update:
  path: /ride-services
  controller: App/EntryPoint/Controller/PutRideServiceController
  methods: [PUT]

drivania_ride_service_list:
  path: /ride-services
  controller: App/EntryPoint/Controller/GetRideServiceController
  methods: [GET]